# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bfleury <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/09/16 17:43:41 by bfleury           #+#    #+#              #
#    Updated: 2015/09/20 08:40:37 by bfleury          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = eval_expr

all: $(NAME)

$(NAME):
	gcc -Wall -Werror -Wextra -o $(NAME) *.c

clean:

fclean: clean
	rm -f $(NAME)

re: fclean all
